services:
  sqlserver:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    container_name: polecat-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@55w0rd"
      MSSQL_PID: "Developer"
    ports:
      - "11433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
